### PR TITLE
replace unlink with dir_delete

### LINKED ISSUE #38: Re-running dependency_table produces error
image

and then running it again produces a different error:

image

### PR DESCRIPTION
**Pull request by nikolas-burkoff**
Closes #38 (see https://github.com/openpharma/staged.dependencies/issues/38#issuecomment-891680364)

Please test on non-Windows machine

### CODE REVIEW

**Comment by nikolas-burkoff** [comment]
Note there's one other unlink in the codebase - not sure if we need to worry about that (I'm just going through Windows Explorer and deleting folders outside of R so it's not as important)

**Comment by waddella** [comment]
@maximilianmordig does not have a windows machine, I have requested @dinakar29 to test it. @nikolas-burkoff can you be a bit more specific what to test?

**Comment by nikolas-burkoff** [comment]
So I've tested it on Windows - want to make sure it doesn't break elsewhere.
Essentially without this the package doesn't work on Windows see here https://github.com/openpharma/staged.dependencies/issues/38

**Review by dinakar29 — APPROVED** [review]

**Comment by dinakar29** [comment]
You could try temporarily incorporating a workflow like this one to check functionality on various OSes:

https://github.com/Roche/respectables/blob/52894a7652c7fe46d09b005bb249c1ee76ac35ff/.github/workflows/build-install-check.yaml

**Pull request merged**
